### ISSUE TITLE
Configure "default inputs" (for default tasks) in the extension

### ISSUE THREAD

**Issue by tbroyer** [sherter/google-java-format-gradle-plugin#11]
Use-case: I'm using Docker to spin up databases I use for development and I mount a folder as a volume where the DB will store its data (that way, I can `rm` the Docker container and keep my data; I could probably use named volumes from Docker Compose version 2 but, well… haven't had time playing with it yet…). The task then chokes on it in its `configure()` because by default it will scan **all** the `projectDir`, and files created by the DB in the container are owned by `root`:

```
$ ./gradlew gJF --stacktrace
:googleJavaFormat

FAILURE: Build failed with an exception.

* What went wrong:
Could not read path '/…/.docker/postgres'.
> /…/.docker/postgres

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.GradleException: Could not read path '/…/.docker/postgres'.
[…]
Caused by: java.nio.file.AccessDeniedException: /…/.docker/postgres
        ... 76 more


BUILD FAILED

Total time: 0.583 secs
```

To get the tasks working, I'd then have to either exclude my `.docker` subdir or include only `src`; but I have to do that on **both** `googleJavaFormat` and `verifyGoogleJavaFormat`. It should be possible to configure both default tasks' default inputs once.
Alternatively, `verifyGoogleJavaFormat` could use a closure calling `googleJavaFormat.source` to inherit the `googleJavaFormat` sources by default:
```groovy
tasks.verifyGoogleJavaFormat.setSource({ tasks.googleJavaFormat.source })
```
(this is something I can use in my build file to easily configure the tasks without duplicating configuration; though I actually use `[tasks.googleJavaFormat, tasks.verifyGoogleJavaFormat].each { task -> … }` to configure both tasks at once)

That said, IMO, the task should use the project's sourcesets as default inputs, rather than "every single `.java` file inside the `projectDir` (but outside the `buildDir`)"; something like `sourceSets*.allJava`; should I file another issue?

In the end, here's what I put in my build:
```gradle
[tasks.googleJavaFormat, tasks.verifyGoogleJavaFormat].each { task ->
  task.source = sourceSets*.allJava
}
```

**Comment by sherter** [comment]
Actually, using source sets was the approach I took in the beginning and then switched to .java files because of issue #3. Please read my comment there, then come back and convince me that we should still default to source sets instead of .java files. I'm open for changes :wink: 

I agree, having to configure both format and verification task is a bit cumbersome...
I don't think inheriting the file set of one task into the other one is a good idea (it's okay to do it explicitly in your build script, but not behind the scenes). Because: what should happen if there actually are different configurations for the tasks? Should we format/check the intersection of both tasks' file sets? The union? Something more complicated, like exclude patterns and include patterns from both tasks applied to the union/intersection of both tasks' sources? This is not obvious and I'd prefer to not have to think about it :wink: 

Adding default sources/includes/excludes to the extension that are then passed on to both tasks as filtered set of source files seems to be a good idea. :+1:
I'm adding this as soon as I find some time...

**Comment by tbroyer** [comment]
> Actually, using source sets was the approach I took in the beginning and then switched to .java files because of issue #3. Please read my comment there, then come back and convince me that we should still default to source sets instead of .java files. I'm open for changes 

How about `allprojects*.file('src/')`? (instead of excluding `allprojects*.buildDir`)

> I agree, having to configure both format and verification task is a bit cumbersome...
> I don't think inheriting the file set of one task into the other one is a good idea (it's okay to do it explicitly in your build script, but not behind the scenes). Because: what should happen if there actually are different configurations for the tasks? Should we format/check the intersection of both tasks' file sets? The union? Something more complicated, like exclude patterns and include patterns from both tasks applied to the union/intersection of both tasks' sources? This is not obvious and I'd prefer to not have to think about it 

Using a convention property could help: if configured, the default value is not used; so it'd be a "replace" rather than "union" or "intersection".
But I agree the best solution is in the extension, hence the issue title :smiley:

> Adding default sources/includes/excludes to the extension that are then passed on to both tasks as filtered set of source files seems to be a good idea. 
> I'm adding this as soon as I find some time...

:+1:

**Comment by sherter** [comment]
> How about allprojects*.file('src/')? (instead of excluding allprojects*.buildDir)

I don't like that too much. Sure, >90% of projects use the convention to put source code into the `src` subdirectory, but Gradle gives people the freedom to choose whatever directory layout they like. I don't want to break that and make any assumptions.

In order to make no such assumptions about file paths, I can really only think of these two options:
* all `.java` files in the project root directory and recursively all subdirectories, excluding `allprojects*.buildDir` (`buildDir` can be set by the user, we don't assume specific paths)
* use `sourceSets*.java`, plus special cases such as `android.sourceSets` and possibly others

The second approach requires dealing with other plugins and plugin application order starts to matter. In case we missed a special case, the files are silently ignored. I'm only aware of one special case though (android), which we can probably deal with.

However, because of it's simplicity and the certainty that we don't miss any files, I still prefer option 1. I'd rather get an exception and add an exclude pattern than silently ignore a file...

**Comment by sherter** [comment]
I released `v0.5`. You can now use the extension object like a task object (call `setSource`, `source`, `include`, `exclude`) and the filtered set of files will then be injected into all tasks (if no other sources were set). For more details, see the updated Readme .

**Comment by tbroyer** [comment]
Tested and approved, thanks!

BTW, the doc should probably use `sourceSets*.allJava` rather than `sourceSets*.java`; that would include Java files in `src/main/groovy` and `src/main/scala` when those are used (and, `sourceSets*.allJava` –as well as `sourceSets*.java`, but probably even more important here– already has a filter to only include `*.java` files so no need to re-add it to `googleJavaFormat` :raised_hands: )

Oh, and I think `source = x` is more idiomatic than `setSource x`.

**Comment by sherter** [comment]
Thanks for the input! Interested in a pull request? :stuck_out_tongue:
I made these examples up and yes, they are pretty bad. Maybe you can change them to a more realistic example? :wink:
