### ISSUE TITLE
Any way to get more verbose output from verifyGoogleJavaFormat?

### ISSUE THREAD

**Issue by loosebazooka** [sherter/google-java-format-gradle-plugin#19]
We have a remote windows test that fails and it would help to debug if verifyGoogleJavaFormat provided some more information on why it was failing?

**Comment by sherter** [comment]
A list of the files that are not formatted properly is logged on the `lifecycle` log level (which is, by default, printed to stdout).  Adding `--info` to the gradle(w) command line will also list the files that _are_ formatted properly. Other than that, there is not much more information we can provide : either `content(file)` _is_ equal to `format(content(file))` or it is _not_ (well, we could print the full diff, but I'm not sure that's a good idea).

In your particular case, I'm guessing the problem is an added/missing carriage return (`\r`). `google-java-format` [changed its behavior](https://github.com/google/google-java-format/issues/33) a while ago to use the platform's line terminator. If you have CI for windows and linux, you should probably turn of the verification step in one of them...

**Comment by loosebazooka** [comment]
@akerekes fyi. Thanks @sherter, yeah we were trying to print the differences, but it looks like we wont be able to. Our new windows CI's git checkout behavior seems to be different than what appveyor was giving us with regards to `\r`.

**Comment by sherter** [comment]
@loosebazooka You can still get the differences by running `gradlew googleJavaFormat && git diff`...

**Comment by loosebazooka** [comment]
Yeah that's what we ended up doing
