### ISSUE TITLE
Problems with end-line on different operating system (Windows and macOS)

### ISSUE THREAD

**Issue by sorina-vasiliu** [sherter/google-java-format-gradle-plugin#21]
Hello,

I'm using google-java-format-gradle-plugin as default standard code formatter for the project that I'm working on. The problem is that some devs are using Windows, other macOS, and "verifyGoogleJavaFormat" task is failing because of end-line differences.Could you help me with this problem?Is there some setting for ignoring the end-line format?

Thanks,
Sorina

**Comment by sherter** [comment]
Which version of `google-java-format` are you using? Since `v1.2` it should [preserve existing line breaks in the output](https://github.com/google/google-java-format/commit/e345bce16276a6c0d8e50ba184b9ae1e02e71478), so it might be sufficient to add 
```
googleJavaFormat {
  toolVersion = '1.3'
}
```
to your `build.gradle`.

Another option would be use `git` to [deal with the line endings](https://help.github.com/articles/dealing-with-line-endings/). `google-java-format` itself doesn't provide an API to change the line separator and I don't particularly like the idea of adding something on top of `google-java-format` to change the line separator...

Let me know if these suggestions don't solve your problem.

**Comment by sorina-vasiliu** [comment]
Thanks for the quick reply.

Unfortunately the project is still on java 7, so I only can use google-java-format v1.1 .

I will try to fix the problem using git settings.
