### ISSUE TITLE
Make Verify Google Java Format Depend On Google Java Format If It Fails

### ISSUE THREAD

**Issue by nishantc1527** [sherter/google-java-format-gradle-plugin#48]
I would really like this built in, as every time it fails I have to manually run google java format. I think you can do something like this:

```
tasks.verifyGoogleJavaFormat {
    onlyIf {
        tasks.verifyGoogleJavaFormat.state.failure != null
    }
    dependsOn {
        tasks.googleJavaFormat
    }
}
```

But I'm not to great at gradle, so I doubt this works. But I think there could be a way to make this work.

**Comment by sherter** [comment]
Are you sure you don't just want to ignore failures? Are you talking about something like #44 / #45 ?

**Comment by nishantc1527** [comment]
Those issues did what I thought of first, which is this line:

    tasks.verifyGoogleJavaFormat.dependsOn(tasks.googleJavaFormat)

However that slowed down my building since it always ran ```googleJavaFormat``` no matter what. I was wondering if it was possible to run ```googleJavaFormat``` only after ```verifyGoogleJavaFormat``` fails.

**Comment by sherter** [comment]
> However that slowed down my building since it always ran `googleJavaFormat` no matter what. I was wondering if it was possible to run `googleJavaFormat` only after `verifyGoogleJavaFormat` fails.

Are you sure about the "slow down" part? Did you measure it? 
Verification is nothing else then _doing_ the formatting (in memory) and comparing it to the actual file content. In fact, it should be _slower_ to do it the way you propose, because the formatted content (in-memory) is discarded after doing the comparison. The `googleJavaFormat` afterwards would have to do the formatting again.

On the other hand, when you run `googleJavaFormat` first, it will only format the files which were added or changed since the last verification/format task run (and files which were found to be not formatted correctly). The verification task afterwards is basically a no-op because we know the files were just formatted by the googleJavaFormat task.

If it really is slower, then please provide measurements results and an example. That is then a bug.

**Comment by sherter** [comment]
(Besides, I still think that what you are trying to do is not a good idea. Do the formatting in a on-save action or a pre-commit hook, but not as part of the `check` task)

**Comment by nishantc1527** [comment]
Thanks for this, sorry to bother you with misinformation since I'm not too good at gradle. I guess it wasn't actually slowing down, I just thought it was.
