### ISSUE TITLE
How to pass JVM args to google-java-format

### ISSUE THREAD

**Issue by lz000** [sherter/google-java-format-gradle-plugin#62]
I need to use google-java-format v1.10.0 to support JDK 16. According to the instruction, I need to pass the following args to JVM. How to do this through the plugin?
```
java \
  --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED \
  -jar google-java-format-1.10.0-all-deps.jar
```

**Comment by sherter** [comment]
You would have to consult the gradle documentation to answer this question. This plugin doesn't spawn any extra JVM processes to run google-java-format, it just loads and uses the classes via reflection.

**Comment by dxxvi** [comment]
@sherter  I have the same issue. Let me put the question in another way: could you please try this plugin with Java 16 when you have some free time? Then you can tell us how you make it work.

Some people told me that it was difficult for them to have another jdk installed on their system because it would mess up everything. I wonder why that can happen because you can download a zip version of the jdk for any operating system from [here](https://www.azul.com/downloads/?package=jdk#download-openjdk), then the last step is `set/export JAVA_HOME=...`.

**Comment by aecio** [comment]
You should be able to do this by creating a file named `gradle.properties` in the root of your project with the following content:
```
org.gradle.jvmargs=--add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
```
This works for me using OpenJDK 17 and Gradle 7.2.

**Comment by sherter** [comment]
Thanks @aecio for providing the solution :+1:
